name: Deploy to IIS

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: GitHub Actions WebDeploy
        uses: cschleiden/webdeploy-action@v1.1.0
        with:
          server: ${{ secrets.IIS_SERVER }}
          siteName: 'mine-care'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.IIS_PASSWORD }}
          physicalPath: 'C:\inetpub\wwwroot\mine-care'
          package: 'build.zip'

