name: Run self hosted server and deploy to IIS folder
# This workflow allows me to controls when the action will run. Triggers the workflow on push to the master branch
# or manually from the Actions tab
# Author: Yassine Hamadou Mounkaila
on:
  push:
    branches:
      - production
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      #      install dependencies only if package.json has changed
      - name: Cache node modules
        # npm cache files on windows
        uses: actions/cache@v2
        with:
          path: 'C:\\Users\\Administrator\\AppData\\Local\\npm-cache'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

        # Checking if the cache hit is not true, if it is true then the dependencies are already installed otherwise we
        # install the dependencies on windows server
      - name: Install Dependencies if windows cache hit is not true
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run ciBuild

      - name: Remove the existing website files except for web.config file
        run: get-childitem 'C:\inetpub\wwwroot\mine-care\' -Exclude *.config -recurse | remove-item -recurse -force

      - name: Copy build folder to the website folder
        run: Copy-Item -Recurse -Force 'build\*' 'C:\inetpub\wwwroot\mine-care'


