name: Deploy to IIS

on: [ push ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Remove the existing website files except for web.config file
        run: Remove-Item -Recurse -Force 'C:\inetpub\wwwroot\mine-care\*' -Exclude 'web.config'

      - name: Copy build folder to the website folder
        run: Copy-Item -Recurse -Force 'build' 'C:\inetpub\wwwroot\mine-care'

      - name: Verifying that the website is running
        run: $response = Invoke-WebRequest -Uri 'http://localhost/mine-care' -UseBasicParsing
          if ($response.StatusCode -ne 200) {
          throw 'Failed to verify that the website is running'
          } else {
          Write-Host 'The website is running'
          }
